### ISSUE TITLE
'introduction' manuscript type added to title (for author submitted manuscript)

### ISSUE THREAD

**Issue by de-code** [allenai/spv2#37]
The following example is from a conversion of the author submitted manuscript (not public unfortunately I believe). The manuscript title is followed by the manuscript type  "Introduction" (both in bold), then the author. The "Introduction" is added to the end of the title.

18968-63868-1-LE.xml "[ejpt thematic cluster: offending behaviour: the role of trauma and ptsd](http://europepmc.org/articles/PMC3402156)"
E: ejpt thematic cluster: offending behaviour: the role of trauma and ptsd
A: ejpt thematic cluster : offending behaviour : the role of trauma and ptsd introduction

(E=expected, A=actual - all in lower case for practical reasons)

**Comment by dirkgr** [comment]
You'll be able to find many documents with extraction errors once you know what to look for. There are some analysis tools to look into some cases in detail, such as the ability to dump tokenized and featurized documents as human-readable HTML.

Sometimes, the problem is with tokenization, featurization, or post-processing. Then, the problem can be fixed like any normal bug.

Sometimes, the problem is in the model, and that's trickier. I believe that the biggest gains in practice will be made by training on a more diverse dataset. The real problems in practice come from documents that are not like PMC documents.
