### ISSUE TITLE
What's the expected performance/benchmark of spv2 against CRF-based approaches?

### ISSUE THREAD

**Issue by davidefiocco** [allenai/spv2#42]
Hi!

I am aware of [GROBID](https://github.com/kermitt2/grobid), which is [benchmarked](https://grobid.readthedocs.io/en/latest/Benchmarking/) in terms of precision/recall against a [publicly available dataset](https://grobid.s3.amazonaws.com/PMC_sample_1943.zip).

Is spv2 expected to be superior? 
Would there be an interest in reproducing benchmarks like those above with spv2, based on a "holdout" evaluation subset of PMC (possibly the very same dataset above)? 
Thanks!

**Comment by dirkgr** [comment]
SPv2 is no longer under active development, but I'd be interested in performance on a held-out set. I'd be excited if you tried it against PMC, but it might not be fair, because that's what we trained SPv2 on :-)

We did our own benchmarks against the first version of this project, https://github.com/allenai/science-parse. That one is CRF based as well. We tuned it until it beat Grobid at the time, but I'm sure Grobid has moved forward since then.

Either way, I'd expect SPv2's performance to be better than either Grobid or science-parse, especially if you evaluate it on medical documents. Because we trained on PMC, SPv2 skews a little medical.
